import "../node_modules/bootstrap/dist/css/bootstrap.min.css"
import 'aos/dist/aos.css';
import "/public/assets/dist/app.css"
import "/public/assets/font/font-awesome.css"
import "/public/assets/dist/swiper-bundle.min.css"
export const metadata = {
  title: 'Monteno - NFT Portfolio Next.js Template',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="header-fixed">{children}</body>
    </html>
  )
}
